apiVersion: v1
kind: Pod
metadata:
  name: kuard-manifest
spec:
  containers:
    - name: kuard-from-manifest
      image: gcr.io/kuar-demo/kuard-arm64:blue
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
          protocol: TCP
  