apiVersion: v1
kind: Pod
metadata:
  name: kuard-manifest
spec:
  volumes:
    - name: tempdata
      emptyDir: {}
    - name: fileFromHost
      hostPath:
        path: "/var/lib/kuard"
  containers:
    - name: kuard-from-manifest
      image: gcr.io/kuar-demo/kuard-arm64:blue
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
          protocol: TCP
      resources:
        requests:
          memory: "128Mi" # MB and MiB are different units
          cpu: "500m" # 500m = 0.5 CPU
        limits:
          memory: "256Mi" # MB and MiB are different units
          cpu: "1000m" # 1000m = 1.0 CPU
      livenessProbe:
        httpGet:
          path: /healthy
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /ready
          port: 8080
        initialDelaySeconds: 30
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
