apiVersion: v1
kind: Pod
metadata:
  name: kuard-manifest
spec:
  containers:
    - name: kuard-from-manifest
      image: gcr.io/kuar-demo/kuard-arm64:blue
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
          protocol: TCP
      resources:
        requests:
          memory: "128Mi" # MB and MiB are different units
          cpu: "500m" # 500m = 0.5 CPU
        limits:
          memory: "256Mi" # MB and MiB are different units
          cpu: "1000m" # 1000m = 1.0 CPU
