apiVersion: v1
kind: Pod
metadata:
  name: kuard-manifest
spec:
  volumes:
    - name: "kuard-data"
      hostPath:
        path: "/var/lib/kuard"
  containers:
    - name: kuard-from-manifest
      image: gcr.io/kuar-demo/kuard-arm64:blue
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
          protocol: TCP
  